embeddings {
  tensor_name: "urg:74624"
  metadata_path: "74624/urg\\metadata.tsv"
  tensor_path: "74624/urg\\tensors.tsv"
}
embeddings {
  tensor_name: "sd_adm:74624"
  metadata_path: "74624/sd_adm\\metadata.tsv"
  tensor_path: "74624/sd_adm\\tensors.tsv"
}
embeddings {
  tensor_name: "oms_ad:74624"
  metadata_path: "74624/oms_ad\\metadata.tsv"
  tensor_path: "74624/oms_ad\\tensors.tsv"
}
embeddings {
  tensor_name: "ew_em:74624"
  metadata_path: "74624/ew_em\\metadata.tsv"
  tensor_path: "74624/ew_em\\tensors.tsv"
}
embeddings {
  tensor_name: "obs:74624"
  metadata_path: "74624/obs\\metadata.tsv"
  tensor_path: "74624/obs\\tensors.tsv"
}
embeddings {
  tensor_name: "ele:74624"
  metadata_path: "74624/ele\\metadata.tsv"
  tensor_path: "74624/ele\\tensors.tsv"
}
embeddings {
  tensor_name: "dir_obs:74624"
  metadata_path: "74624/dir_obs\\metadata.tsv"
  tensor_path: "74624/dir_obs\\tensors.tsv"
}
embeddings {
  tensor_name: "dir_em:74624"
  metadata_path: "74624/dir_em\\metadata.tsv"
  tensor_path: "74624/dir_em\\tensors.tsv"
}
embeddings {
  tensor_name: "amb_obs:74624"
  metadata_path: "74624/amb_obs\\metadata.tsv"
  tensor_path: "74624/amb_obs\\tensors.tsv"
}
embeddings {
  tensor_name: "is_male:74624"
  metadata_path: "74624/is_male\\metadata.tsv"
  tensor_path: "74624/is_male\\tensors.tsv"
}
embeddings {
  tensor_name: "blood:74624"
  metadata_path: "74624/blood\\metadata.tsv"
  tensor_path: "74624/blood\\tensors.tsv"
}
embeddings {
  tensor_name: "circulatory:74624"
  metadata_path: "74624/circulatory\\metadata.tsv"
  tensor_path: "74624/circulatory\\tensors.tsv"
}
embeddings {
  tensor_name: "congenital:74624"
  metadata_path: "74624/congenital\\metadata.tsv"
  tensor_path: "74624/congenital\\tensors.tsv"
}
embeddings {
  tensor_name: "digestive:74624"
  metadata_path: "74624/digestive\\metadata.tsv"
  tensor_path: "74624/digestive\\tensors.tsv"
}
embeddings {
  tensor_name: "endocrine:74624"
  metadata_path: "74624/endocrine\\metadata.tsv"
  tensor_path: "74624/endocrine\\tensors.tsv"
}
embeddings {
  tensor_name: "genitourinary:74624"
  metadata_path: "74624/genitourinary\\metadata.tsv"
  tensor_path: "74624/genitourinary\\tensors.tsv"
}
embeddings {
  tensor_name: "infectious:74624"
  metadata_path: "74624/infectious\\metadata.tsv"
  tensor_path: "74624/infectious\\tensors.tsv"
}
embeddings {
  tensor_name: "injury:74624"
  metadata_path: "74624/injury\\metadata.tsv"
  tensor_path: "74624/injury\\tensors.tsv"
}
embeddings {
  tensor_name: "mental:74624"
  metadata_path: "74624/mental\\metadata.tsv"
  tensor_path: "74624/mental\\tensors.tsv"
}
embeddings {
  tensor_name: "misc:74624"
  metadata_path: "74624/misc\\metadata.tsv"
  tensor_path: "74624/misc\\tensors.tsv"
}
embeddings {
  tensor_name: "muscular:74624"
  metadata_path: "74624/muscular\\metadata.tsv"
  tensor_path: "74624/muscular\\tensors.tsv"
}
embeddings {
  tensor_name: "neoplasms:74624"
  metadata_path: "74624/neoplasms\\metadata.tsv"
  tensor_path: "74624/neoplasms\\tensors.tsv"
}
embeddings {
  tensor_name: "nervous:74624"
  metadata_path: "74624/nervous\\metadata.tsv"
  tensor_path: "74624/nervous\\tensors.tsv"
}
embeddings {
  tensor_name: "pregnancy:74624"
  metadata_path: "74624/pregnancy\\metadata.tsv"
  tensor_path: "74624/pregnancy\\tensors.tsv"
}
embeddings {
  tensor_name: "perinatal:74624"
  metadata_path: "74624/perinatal\\metadata.tsv"
  tensor_path: "74624/perinatal\\tensors.tsv"
}
embeddings {
  tensor_name: "respiratory:74624"
  metadata_path: "74624/respiratory\\metadata.tsv"
  tensor_path: "74624/respiratory\\tensors.tsv"
}
embeddings {
  tensor_name: "skin:74624"
  metadata_path: "74624/skin\\metadata.tsv"
  tensor_path: "74624/skin\\tensors.tsv"
}
